export const COUNTRIES_DATA = [
  { name: "BRASIL", phrase: "Bom dia, tudo bem?", continent: "America do Sul", hemisphere: "Sul", population: 216000000 },
  { name: "COLOMBIA", phrase: "Buenos días, ¿cómo estás?", continent: "America do Sul", hemisphere: "Norte", population: 52000000 },
  { name: "ARGENTINA", phrase: "Buenos días, ¿cómo estás?", continent: "America do Sul", hemisphere: "Sul", population: 46000000 },
  { name: "CHILE", phrase: "Buenos días, ¿cómo estás?", continent: "America do Sul", hemisphere: "Sul", population: 19500000 },
  { name: "PERU", phrase: "Buenos días, ¿cómo estás?", continent: "America do Sul", hemisphere: "Sul", population: 34000000 },
  { name: "FRANCA", phrase: "Bonjour, comment allez-vous?", continent: "Europa", hemisphere: "Norte", population: 68000000 },
  { name: "CANADA", phrase: "Good morning, how are you?", continent: "America do Norte", hemisphere: "Norte", population: 40000000 },
  { name: "ESTADOS UNIDOS", phrase: "Good morning, how are you?", continent: "America do Norte", hemisphere: "Norte", population: 335000000 },
  { name: "MEXICO", phrase: "Buenos días, ¿cómo estás?", continent: "America do Norte", hemisphere: "Norte", population: 128000000 },
  { name: "JAPAO", phrase: "おはようございます", continent: "Asia", hemisphere: "Norte", population: 123000000 },
  { name: "CHINA", phrase: "早上好，你好吗？", continent: "Asia", hemisphere: "Norte", population: 1410000000 },
  { name: "COREIA DO SUL", phrase: "안녕하세요, 어떻게 지내세요?", continent: "Asia", hemisphere: "Norte", population: 51700000 },
  { name: "INDIA", phrase: "सुप्रभात, आप कैसे हैं?", continent: "Asia", hemisphere: "Norte", population: 1428000000 },
  { name: "TAILANDIA", phrase: "สวัสดีตอนเช้า สบายดีไหม", continent: "Asia", hemisphere: "Norte", population: 71000000 },
  { name: "VIETNA", phrase: "Chào buổi sáng, bạn khỏe không?", continent: "Asia", hemisphere: "Norte", population: 98000000 },
  { name: "INDONESIA", phrase: "Selamat pagi, apa kabar?", continent: "Asia", hemisphere: "Sul", population: 278000000 },
  { name: "EGITO", phrase: "صباح الخير، كيف حالك؟", continent: "Africa", hemisphere: "Norte", population: 112000000 },
  { name: "ARABIA SAUDITA", phrase: "صباح الخير، كيف حالك؟", continent: "Asia", hemisphere: "Norte", population: 36000000 },
  { name: "MARROCOS", phrase: "صباح الخير، كيف حالك؟", continent: "Africa", hemisphere: "Norte", population: 37000000 },
  { name: "ISRAEL", phrase: "בוקר טוב, מה שלומך?", continent: "Asia", hemisphere: "Norte", population: 9700000 },
  { name: "TURQUIA", phrase: "Günaydın, nasılsın?", continent: "Asia", hemisphere: "Norte", population: 85000000 },
  { name: "GRECIA", phrase: "Καλημέρα, πώς είσαι;", continent: "Europa", hemisphere: "Norte", population: 10400000 },
  { name: "RUSSIA", phrase: "Доброе утро, как дела?", continent: "Europa", hemisphere: "Norte", population: 144000000 },
  { name: "ALEMANHA", phrase: "Guten Morgen, wie geht es Ihnen?", continent: "Europa", hemisphere: "Norte", population: 84000000 },
  { name: "ITALIA", phrase: "Buongiorno, come stai?", continent: "Europa", hemisphere: "Norte", population: 59000000 },
  { name: "PORTUGAL", phrase: "Bom dia, tudo bem?", continent: "Europa", hemisphere: "Norte", population: 10300000 },
  { name: "ESPANHA", phrase: "Buenos días, ¿cómo estás?", continent: "Europa", hemisphere: "Norte", population: 47500000 },
  { name: "HOLANDA", phrase: "Goedemorgen, hoe gaat het?", continent: "Europa", hemisphere: "Norte", population: 17900000 },
  { name: "SUECIA", phrase: "God morgon, hur mår du?", continent: "Europa", hemisphere: "Norte", population: 10500000 },
  { name: "POLONIA", phrase: "Dzień dobry, jak się masz?", continent: "Europa", hemisphere: "Norte", population: 37700000 },
  { name: "UCRANIA", phrase: "Доброго ранку, як справи?", continent: "Europa", hemisphere: "Norte", population: 36700000 },
  { name: "AFRICA DO SUL", phrase: "Goeie môre, hoe gaan dit?", continent: "Africa", hemisphere: "Sul", population: 60000000 },
  { name: "NIGERIA", phrase: "Good morning, how are you?", continent: "Africa", hemisphere: "Norte", population: 223000000 },
  { name: "QUENIA", phrase: "Habari za asubuhi, u hali gani?", continent: "Africa", hemisphere: "Sul", population: 55000000 },
  { name: "ETIOPIA", phrase: "እንደምን አደርክ?", continent: "Africa", hemisphere: "Norte", population: 126000000 },
  { name: "ANGOLA", phrase: "Bom dia, tudo bem?", continent: "Africa", hemisphere: "Sul", population: 36700000 },
  { name: "MOCAMBIQUE", phrase: "Bom dia, tudo bem?", continent: "Africa", hemisphere: "Sul", population: 33000000 },
  { name: "AUSTRALIA", phrase: "Good morning, how are you?", continent: "Oceania", hemisphere: "Sul", population: 26600000 },
  { name: "NOVA ZELANDIA", phrase: "Good morning, how are you?", continent: "Oceania", hemisphere: "Sul", population: 5200000 },
  { name: "REINO UNIDO", phrase: "Good morning, how are you?", continent: "Europa", hemisphere: "Norte", population: 68000000 },
];