export const COUNTRIES_DATA = [
  { name: "BRASIL", phrase: "Bom dia, tudo bem?", continent: "America do Sul", hemisphere: "Sul", population: 216000000 },
  { name: "COLÔMBIA", phrase: "Buenos días, ¿cómo estás?", continent: "America do Sul", hemisphere: "Norte", population: 52000000 },
  { name: "ARGENTINA", phrase: "Buenos días, ¿cómo estás?", continent: "America do Sul", hemisphere: "Sul", population: 46000000 },
  { name: "CHILE", phrase: "Buenos días, ¿cómo estás?", continent: "America do Sul", hemisphere: "Sul", population: 19500000 },
  { name: "PERU", phrase: "Buenos días, ¿cómo estás?", continent: "America do Sul", hemisphere: "Sul", population: 34000000 },
  { name: "FRANÇA", phrase: "Bonjour, comment allez-vous?", continent: "Europa", hemisphere: "Norte", population: 68000000 },
  { name: "CANADÁ", phrase: "Good morning, how are you?", continent: "America do Norte", hemisphere: "Norte", population: 40000000 },
  { name: "ESTADOS UNIDOS", phrase: "Good morning, how are you?", continent: "America do Norte", hemisphere: "Norte", population: 335000000 },
  { name: "MÉXICO", phrase: "Buenos días, ¿cómo estás?", continent: "America do Norte", hemisphere: "Norte", population: 128000000 },
  { name: "JAPÃO", phrase: "おはようございます", continent: "Asia", hemisphere: "Norte", population: 123000000 },
  { name: "CHINA", phrase: "早上好，你好吗？", continent: "Asia", hemisphere: "Norte", population: 1410000000 },
  { name: "CORÉIA DO SUL", phrase: "안녕하세요, 어떻게 지내세요?", continent: "Asia", hemisphere: "Norte", population: 51700000 },
  { name: "INDIA", phrase: "सुप्रभात, आप कैसे हैं?", continent: "Asia", hemisphere: "Norte", population: 1428000000 },
  { name: "TAILÂNDIA", phrase: "สวัสดีตอนเช้า สบายดีไหม", continent: "Asia", hemisphere: "Norte", population: 71000000 },
  { name: "VIETNÃ", phrase: "Chào buổi sáng, bạn khỏe không?", continent: "Asia", hemisphere: "Norte", population: 98000000 },
  { name: "INDONÉSIA", phrase: "Selamat pagi, apa kabar?", continent: "Asia", hemisphere: "Sul", population: 278000000 },
  { name: "EGITO", phrase: "صباح الخير، كيف حالك؟", continent: "Africa", hemisphere: "Norte", population: 112000000 },
  { name: "ARÁBIA SAUDITA", phrase: "صباح الخير، كيف حالك؟", continent: "Asia", hemisphere: "Norte", population: 36000000 },
  { name: "MARROCOS", phrase: "صباح الخير، كيف حالك؟", continent: "Africa", hemisphere: "Norte", population: 37000000 },
  { name: "ISRAEL", phrase: "בוקר טוב, מה שלומך?", continent: "Asia", hemisphere: "Norte", population: 9700000 },
  { name: "TURQUIA", phrase: "Günaydın, nasılsın?", continent: "Asia", hemisphere: "Norte", population: 85000000 },
  { name: "GRÉCIA", phrase: "Καλημέρα, πώς είσαι;", continent: "Europa", hemisphere: "Norte", population: 10400000 },
  { name: "RUSSIA", phrase: "Доброе утро, как дела?", continent: "Europa", hemisphere: "Norte", population: 144000000 },
  { name: "ALEMANHA", phrase: "Guten Morgen, wie geht es Ihnen?", continent: "Europa", hemisphere: "Norte", population: 84000000 },
  { name: "ITÁLIA", phrase: "Buongiorno, come stai?", continent: "Europa", hemisphere: "Norte", population: 59000000 },
  { name: "PORTUGAL", phrase: "Bom dia, tudo bem?", continent: "Europa", hemisphere: "Norte", population: 10300000 },
  { name: "ESPANHA", phrase: "Buenos días, ¿cómo estás?", continent: "Europa", hemisphere: "Norte", population: 47500000 },
  { name: "HOLANDA", phrase: "Goedemorgen, hoe gaat het?", continent: "Europa", hemisphere: "Norte", population: 17900000 },
  { name: "SUÉCIA", phrase: "God morgon, hur mår du?", continent: "Europa", hemisphere: "Norte", population: 10500000 },
  { name: "POLÔNIA", phrase: "Dzień dobry, jak się masz?", continent: "Europa", hemisphere: "Norte", population: 37700000 },
  { name: "UCRÂNIA", phrase: "Доброго ранку, як справи?", continent: "Europa", hemisphere: "Norte", population: 36700000 },
  { name: "ÁFRICA DO SUL", phrase: "Goeie môre, hoe gaan dit?", continent: "Africa", hemisphere: "Sul", population: 60000000 },
  { name: "NIGERIA", phrase: "Good morning, how are you?", continent: "Africa", hemisphere: "Norte", population: 223000000 },
  { name: "QUENIA", phrase: "Habari za asubuhi, u hali gani?", continent: "Africa", hemisphere: "Sul", population: 55000000 },
  { name: "ETIÓPIA", phrase: "እንደምን አደርክ?", continent: "Africa", hemisphere: "Norte", population: 126000000 },
  { name: "ANGOLA", phrase: "Bom dia, tudo bem?", continent: "Africa", hemisphere: "Sul", population: 36700000 },
  { name: "MOÇAMBIQUE", phrase: "Bom dia, tudo bem?", continent: "Africa", hemisphere: "Sul", population: 33000000 },
  { name: "AUSTRALIA", phrase: "Good morning, how are you?", continent: "Oceania", hemisphere: "Sul", population: 26600000 },
  { name: "NOVA ZELÂNDIA", phrase: "Good morning, how are you?", continent: "Oceania", hemisphere: "Sul", population: 5200000 },
  { name: "REINO UNIDO", phrase: "Good morning, how are you?", continent: "Europa", hemisphere: "Norte", population: 68000000 },
  { name: "FILIPINAS", phrase: "Magandang umaga, kumusta ka?", continent: "Asia", hemisphere: "Norte", population: 117000000 },
  { name: "MALÁSIA", phrase: "Selamat pagi, apa khabar?", continent: "Asia", hemisphere: "Norte", population: 34000000 },
  { name: "PAQUISTÃO", phrase: "صبح بخیر، آپ کیسے ہیں؟", continent: "Asia", hemisphere: "Norte", population: 240000000 },
  { name: "BANGLADESH", phrase: "সুপ্রভাত, আপনি কেমন আছেন?", continent: "Asia", hemisphere: "Norte", population: 173000000 },
  { name: "IRÃ", phrase: "صبح بخیر، حال شما چطور است؟", continent: "Asia", hemisphere: "Norte", population: 89000000 },
  { name: "FINLÂNDIA", phrase: "Hyvää huomenta, mitä kuuluu?", continent: "Europa", hemisphere: "Norte", population: 5600000 },
  { name: "NORUEGA", phrase: "God morgen, hvordan har du det?", continent: "Europa", hemisphere: "Norte", population: 5500000 },
  { name: "DINAMARCA", phrase: "Godmorgen, hvordan har du det?", continent: "Europa", hemisphere: "Norte", population: 5900000 },
  { name: "HUNGRIA", phrase: "Jó reggelt, hogy vagy?", continent: "Europa", hemisphere: "Norte", population: 9700000 },
  { name: "ROMÊNIA", phrase: "Bună dimineața, ce mai faci?", continent: "Europa", hemisphere: "Norte", population: 19000000 },
  { name: "REPÚBLICA CHECA", phrase: "Dobré ráno, jak se máš?", continent: "Europa", hemisphere: "Norte", population: 10700000 },
  { name: "SUÍÇA", phrase: "Guten Morgen, wie geht es dir?", continent: "Europa", hemisphere: "Norte", population: 8800000 },
  { name: "TANZÂNIA", phrase: "Habari za asubuhi, hujambo?", continent: "Africa", hemisphere: "Sul", population: 67000000 },
  { name: "GANA", phrase: "Good morning, how are you?", continent: "Africa", hemisphere: "Norte", population: 34000000 },
  { name: "SENEGAL", phrase: "Bonjour, comment allez-vous?", continent: "Africa", hemisphere: "Norte", population: 18000000 },
];