export const FLAGS_DATA = [
  { name: "União Soviética", flagFile: "urss.svg", period: "1922–1991", region: "Europa/Ásia" },
  { name: "Iugoslávia", flagFile: "iugoslavia.svg", period: "1945–1992", region: "Europa" },
  { name: "Alemanha Oriental", flagFile: "rda.svg", period: "1949–1990", region: "Europa" },
  { name: "Reino da Prússia", flagFile: "prussia.svg", period: "1701–1918", region: "Europa" },
  { name: "Império Otomano", flagFile: "otomano.svg", period: "1299–1922", region: "Europa/Ásia" },
  { name: "Estados Confederados da América", flagFile: "confederado.svg", period: "1861–1865", region: "América do Norte" },
  { name: "Rodésia", flagFile: "rodesia.svg", period: "1965–1979", region: "África" },
  { name: "Zaire", flagFile: "zaire.svg", period: "1971–1997", region: "África" },
  { name: "Tchecoslováquia", flagFile: "tcheco.svg", period: "1918–1992", region: "Europa" },
  { name: "Império Austro-Húngaro", flagFile: "austro-hungaro.svg", period: "1867–1918", region: "Europa" },
  { name: "Estados Unidos do Brasil", flagFile: "brazil-republic.svg", period: "1889", region: "América do Sul" },
  { name: "Império do Japão", flagFile: "japan.svg", period: "1868–1945", region: "Ásia" },
  { name: "Biafra", flagFile: "biafra.svg", period: "1967–1970", region: "África" },
  { name: "Raj Britânico", flagFile: "british-raj.svg", period: "1858–1947", region: "Ásia" },
  { name: "Reino do Egito", flagFile: "egypt.svg", period: "1922–1953", region: "África" },
  { name: "Império da Etiópia", flagFile: "ethiopia.svg", period: "1897–1974", region: "África" },
  { name: "Estados Unidos da Indonésia", flagFile: "indonesia.svg", period: "1949–1950", region: "Ásia" },
  { name: "Estado Livre da Irlanda", flagFile: "ireland.svg", period: "1922–1937", region: "Europa" },
  { name: "Manchukuo", flagFile: "manchukuo.svg", period: "1932–1945", region: "Ásia" },
  { name: "União Polaco-Lituana", flagFile: "poland-lithuania-2.svg", period: "1569–1795", region: "Europa" },
  { name: "União Sul-Africana", flagFile: "south-africa.svg", period: "1910–1961", region: "África" },
  { name: "Vietnã do Sul", flagFile: "south-vietnam.svg", period: "1955–1975", region: "Ásia" },
  { name: "Iêmen do Sul", flagFile: "south-yemen.svg", period: "1967–1990", region: "Oriente Médio" },
  { name: "Reino das Duas Sicílias", flagFile: "two-sicilies.svg", period: "1816–1861", region: "Europa" },
  { name: "República de Veneza", flagFile: "venice-republic.svg", period: "697–1797", region: "Europa" },
];